# Generated by Django 4.1.6 on 2023-03-16 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cusine', models.CharField(max_length=250)),
                ('cusineid', models.IntegerField(default=None, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=750)),
                ('cusineid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restaurant.cuisine')),
            ],
        ),
    ]
